In [1]:
# import the necessary libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [2]:
## import and read the dataset
data=pd.read_csv('credit_card.csv')
data.head()

,actionnr,merchant_id,average_amount_transaction_day,transaction_amount,is_declined,total_number_of_declines_day,isforeigntransaction,ishighriskcountry,daily_chargeback_avg_amt,sixmonth_avg_chbk_amt,sixmonth_chbk_freq,isfradulent
0,1,3160040998,100.0,3000.0,N,5,Y,Y,0,0.0,0,Y
1,2,3160040998,100.0,4300.0,N,5,Y,Y,0,0.0,0,Y
2,3,3160041896,185.5,4823.0,Y,5,N,N,0,0.0,0,Y
3,4,3160141996,185.5,5008.5,Y,8,N,N,0,0.0,0,Y
4,5,3160241992,500.0,26000.0,N,0,Y,Y,800,677.2,6,Y

In [ ]:
##

In [3]:
type(data)

pandas.core.frame.DataFrame

In [4]:
# Remove the target column from the dataset
data=data.drop(columns=['isfradulent','actionnr','merchant_id'])
data.head()

,merchant_id,average_amount_transaction_day,transaction_amount,is_declined,total_number_of_declines_day,isforeigntransaction,ishighriskcountry,daily_chargeback_avg_amt,sixmonth_avg_chbk_amt,sixmonth_chbk_freq
0,3160040998,100.0,3000.0,N,5,Y,Y,0,0.0,0
1,3160040998,100.0,4300.0,N,5,Y,Y,0,0.0,0
2,3160041896,185.5,4823.0,Y,5,N,N,0,0.0,0
3,3160141996,185.5,5008.5,Y,8,N,N,0,0.0,0
4,3160241992,500.0,26000.0,N,0,Y,Y,800,677.2,6

In [7]:
## Identify the dataframe structure to  evaluvate meta data, assess the data quality, and understand of the dataset composition
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3075 entries, 0 to 3074
Data columns (total 10 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   merchant_id                     3075 non-null   int64
 1   average_amount_transaction_day  3075 non-null   float64
 2   transaction_amount              3075 non-null   float64
 3   is_declined                     3075 non-null   object
 4   total_number_of_declines_day    3075 non-null   int64
 5   isforeigntransaction            3075 non-null   object
 6   ishighriskcountry               3075 non-null   object
 7   daily_chargeback_avg_amt        3075 non-null   int64
 8   sixmonth_avg_chbk_amt           3075 non-null   float64
 9   sixmonth_chbk_freq              3075 non-null   int64
dtypes: float64(3), int64(4), object(3)
memory usage: 240.4+ KB